# Runs compatibiility tests

name: Backward Compatibility Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node: ["12.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout tkey repo
        uses: actions/checkout@v2
        with:
          repository: tkey/tkey
          path: ./tkey

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Set output of cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Node dependency cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-
        
      - name: Go into tkey repo
        run: |
          ls
          cd ./tkey
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bootstrap dependencies
        run: yarn run bootstrap

      - name: Test Development
        run: yarn run test
      
#       - name: Pack
#         run: yarn run pack:lerna
      
      - name: go back out
        run: cd ..
        
      - name: clone comp tests
        uses: actions/checkout@master
        with:
          repository: tkey/backward-compatibility-tests
          path: ./backward-compatibility-tests
      
      - name: go into comp tests
        run: |
          cd ./backward-compatibility-tests
          npm i
          for filename in ../tkey/packages/* ; do
            echo "installing $filename" || continue
            # ... install packed packages
            npm i "${filename}"
          done
          
      - name: run comp tests
        run: npm test
          



          
